# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: cron wf wrapper

on:
  schedule:
    # min hourGMT dom mon dow
    - cron: '45 13 * * *'
    # debug run
    #- cron: '5 11 * * *'
  workflow_dispatch:

jobs:
  cron-wf-trig:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        branch: [ 'master' ]
        profile: [ 'narodni-repozitar-test', 'narodni-repozitar' ]
    steps:
      - name: test run ${{ matrix.branch }} / ${{ matrix.profile }}
        run: |
          echo "${{ matrix.branch }} / ${{ matrix.profile }}"
      - name: Trig workflow in ${{ matrix.branch }} br.
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: 31271525
          token: ${{ secrets.TH_BOT_220729 }}
          ref: ${{ matrix.branch }}
          inputs: '{ "profile": "${{ matrix.profile }}" }'
