# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: version bump, w.cron supp.

on:
  schedule:
    # every sat. at 7:51 GMT
    - cron: '51 7 * * 6'
    # debug run
    #- cron: '10 17 * * *'
    #- cron: '50 7 * * 5'
  workflow_dispatch:

jobs:
  cron-wf-trig:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        branch: [ 'master' ]
    env:
      BRANCH: ${{ matrix.branch }}
      PYPROJECT: "./pyproject.toml"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install bump
        run: |
          pip install bump
      - name: get bumped version
        run: |
          # extract version from pyproject.toml:
          VER=$(sed -n '/^version = / {s/^[^\x27"]\+[\x27"]\([0-9a-z\.]\+\)[\x27"]$/\1/;p}' "${{ env.PYPROJECT }}")
          MAJOR=$(sed -n '/^version = / {s/^[^\x27"]\+[\x27"]\([0-9]\+\)\.[0-9\.a-z]\+[\x27"]$/\1/;p}' "${{ env.PYPROJECT }}")
          VER4BUMP=$(sed -n '/^version = / {s/^\([^\x27"]\+[\x27"]\)[0-9]\+\.\([0-9\.]\+\)[\.a-z]\([0-9]\+[\x27"]\)$/\1\2.\3/;p}' "${{ env.PYPROJECT }}")
          echo "oldver:$VER; major:$MAJOR; ver4bump:$VER4BUMP"
          NEWVER="$MAJOR.$(echo "$VER4BUMP" | bump - /dev/null)"
          echo "bump from '$VER' to '$NEWVER'"
          sed -i '/^version = / { s/\([\x27"]\)[0-9a-z.]\+\([\x27"]\)/\1$NEWVER\2/ }" "${{ env.PYPROJECT }}"
          git diff
          grep -E '^version' "${{ env.PYPROJECT }}"
