name: Build Python Application with PyInstaller

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        #os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          #pip install pyinstaller pysimplegui pyside2 wxPython
          pip install pyinstaller pysimplegui wxPython
          #pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: |
          PYLIBS=$(python -c 'import site; print(site.getsitepackages()[0])')
          echo "PYLIBS: ${PYLIBS}"
          #pyinstaller --onefile --windowed your_script.py
          pyinstaller --onefile --paths=${PYLIBS} ./python/PySimpleGUI_1.py
          #pyinstaller --onefile --paths=${PYLIBS} ./python/PySide_1.py
          pyinstaller --onefile --paths=${PYLIBS} ./python/wxPython_1.py
          #pyinstaller --onefile --paths=${PYLIBS} ./python/wxPython_2.py
        shell: bash  # Na macOS použijeme bash

      - name: Archive build output (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: ./dist

      - name: Archive build output (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: ./dist

      - name: Archive build output (macOS)
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: ./dist

