
name: Matrix test 2

on:
  workflow_call:
    inputs:
      oarepo:
        description: OARepo version (11, 12, ...)
        required: true
        default: 11
        type: string
  workflow_dispatch:
    inputs:
      oarepo:
        description: OARepo version (11, 12, ...)
        required: true
        default: 11

jobs:
  ver-check:
    runs-on: ubuntu-latest
    env:
      OAREPO_VERSION: ${{ github.event.inputs.oarepo }}
      TOK: ${{ secrets.OAREPO_BOT }}
      MATRIX: {"oarepo-library:":[{"name":"oarepo/oarepo-runtime"},{"name":"oarepo/oarepo-upload-cli"},{"name":"Narodni-repozitar/nr-model"},],"python-version:":[{"name":"3.10"}]}
    strategy:
      matrix: ${{ fromJson(env.MATRIX) }}
    steps:
      - name: Print output
        run: |
          echo "Output: ${{ matrix.oarepo-library }}"
