
name: Matrix test 2

on:
  workflow_call:
    inputs:
      oarepo:
        description: OARepo version (11, 12, ...)
        required: true
        default: 11
        type: string
  workflow_dispatch:
    inputs:
      oarepo:
        description: OARepo version (11, 12, ...)
        required: true
        default: 11

jobs:
  get-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set matrix
        id: set-matrix
        run: echo "matrix=$(jq -c . < ./libraries.json)" >> $GITHUB_OUTPUT
      - name: debug
        run: jq '.' <<<'${{ steps.set-matrix.outputs.matrix }}'

  print:
    runs-on: ubuntu-latest
    needs: get-matrix
    strategy:
      matrix:
        python-version: "3.10"
        include: ${{ fromJson(needs.get-matrix.outputs.matrix) }}
    env:
      OAREPO_VERSION: ${{ github.event.inputs.oarepo }}
      TOK: ${{ secrets.OAREPO_BOT }}
    steps:
      - name: Print output
        run: |
          echo "Output: ${{ matrix.library }}"
          echo ">${{ toJson(matrix) }}<"
