name: Matrix test 2

on:
  workflow_call:
    inputs:
      oarepo:
        description: OARepo version (11, 12, ...)
        required: true
        default: 11
        type: string
  workflow_dispatch:
    inputs:
      oarepo:
        description: OARepo version (11, 12, ...)
        required: true
        default: 11

jobs:
  load-matrix-job:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.load-matrix.outputs.matrix }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set matrix
        id: load-matrix
        run: echo "matrix=$(jq -c . < ./libraries.json)" >> $GITHUB_OUTPUT
      - name: debug
        run: |
          echo "matrix: >${{ steps.load-matrix.outputs.matrix }}<"
          echo "json:"
          jq '.' <<<'${{ steps.load-matrix.outputs.matrix }}'

  process-matrix-job:
    runs-on: ubuntu-latest
    needs: load-matrix-job
    strategy:
      matrix:
        library: ${{ fromJson(needs.load-matrix-job.outputs.matrix) }}
        python-version: [ "3.10" ]
    env:
      OAREPO_VERSION: ${{ github.event.inputs.oarepo }}
      TOK: ${{ secrets.OAREPO_BOT }}
      BOT: oarepo-bot
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Print matrix
        run: |
          echo "matrix.library: ${{ matrix.library }}"
          echo "matrix: >${{ matrix }}<"
          echo "json: >${{ toJson(matrix) }}<"
      - name: get default branch for ${{ matrix.library }}
        run: |
          REPO="${{ matrix.library }}"
          BASE_URL="https://api.github.com/repos/$REPO"
          . ./scripts/functions.sh
          BASE_URL2="https://github.com/$REPO"
          echo -e "\n$REPO\n($BASE_URL2)\nget default branch:"
          BR=$(curl -s -XGET -H "Accept: application/json" "$BASE_URL2" | jq -r '.payload.repo.defaultBranch')
          echo " ... branch $BR"
          echo "BR=$BR" >> $GITHUB_ENV
      - name: get trigrun for ${{ matrix.library }}
        run: |
          REPO="${{ matrix.library }}"
          BASE_URL="https://api.github.com/repos/$REPO"
          . ./scripts/functions.sh
          echo "api_get_trigrun (for $REPO):"
          api_get_trigrun "$BASE_URL"
