# This is a basic workflow to help you get started with Actions

name: test1_wf1

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths: [ 'comm2test2/*' ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    #- name: Run a multi-line script
    #  run: |
    #    echo Test of the action publish-to-git
    - uses: seanmiddleditch/gha-publish-to-git@master
      with:
        repository: thlava-cesnet/test2
        branch: from_test1
#        github_token: '${{ secrets.GITHUB_TOKEN }}'
        github_pat: '${{ secrets.TOK }}'
        source_folder: comm2test2
        target_folder: commFtest1
      #if: success() && github.event == 'push'
      