# This is a basic workflow to help you get started with Actions

name: wf3-af

on:
  push:
    branches: [ master ]
    paths: [ 'wf3-af-trig.txt' ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - id: actions-test-action1-call
      name: 'actions-test/action1 call'
      uses: thlava-cesnet/actions-test@v1
      with:
        input1: 'wf3-INPUT1'
    - name: Success test step
      run: |
        echo "Success test (output: ${{ steps.actions-test-action1-call.outputs.output1 }})"
      if: success()
      