name: New RFC

on:
  workflow_dispatch:
    inputs:
      issuenum:
        description: Issue number
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      ISN: ${{ github.event.inputs.issuenum }}
      ISN2: 12
      TEMPLATE: 0000-template.md
      APIURL: https://api.github.com/repos/thlava-cesnet/test1/issues
    steps:
      - name: Checkout oarepo/rfcs
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TH_BOT }}
      - name: with input "#"${{ github.event.inputs.issuenum }}
        run: |
          echo "Test of input, issuenum:${{ github.event.inputs.issuenum }}"
          printf -v ISN_Z "%04d" "$ISN"
          DATE=$(date '+%Y-%m-%d')
          TITLE0="$(curl -s "$APIURL/$ISN2" | jq -r '.title')"
          TITLE="${TITLE0##\[*\] }"
          TITLE="${TITLE,,}"
          TITLE="${TITLE/ / -}"
          AUTHOR="$(curl -s "$APIURL/$ISN2" | jq -r '.user.login')"
          DOC="docs/$ISN_Z-$TITLE.md"
          echo "$DOC - $TITLE0 ($TITLE) [$AUTHOR]"
          echo "----"
          curl -s "$APIURL/$ISN2"
          echo "---- title, login"
          echo "----"
          echo "ISN_Z=$ISN_Z" >> $GITHUB_ENV
          echo "BRANCH=rfc-$ISN_Z" >> $GITHUB_ENV
          echo "DOC=$DOC" >> $GITHUB_ENV
          cp $TEMPLATE "$DOC"
          sed -i "/^- Start Date:/ s/YYYY-MM-DD/$DATE/" "$DOC"
          sed -i "/^- Authors:/ s/:/: $AUTHOR/" "$DOC"
          sed -i "/^# <RFC title>/ s/<RFC title>/$TITLE0/" "$DOC"
#      - name: Commit back
#        run: |
#          echo "Start [$BRANCH]"
#          git config --global user.name oarepo-bot
#          git config --global user.email noreply@cesnet.cz
#          git checkout -b "$BRANCH"
#          git add "$DOC"
#          git commit -m "commit $ISN_Z"
#          git push --set-upstream origin "$BRANCH"
#          echo "Done."
      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TH_BOT }}
          commit-message: "init - close #${{ env.ISN2 }}"
          committer: oarepo-bot <noreply@cesnet.cz>
          body: "PR for issue #${{ env.ISN }}"
          title: '[Test] PR for issue ${{ env.ISN }} '
          branch: ${{ env.BRANCH }}
      - name: Outputs
        run: |
          echo "#${{ steps.cpr.outputs.pull-request-number }}"
          echo "${{ steps.cpr.outputs.pull-request-url }}"
      - name: Commit back
        run: |
          PRN=${{ steps.cpr.outputs.pull-request-number }}
          PR_URL=${{ steps.cpr.outputs.pull-request-url }}
          sed -i "/^- RFC PR:/ { s/<PR>/$PRN/g ; s/(.*)/(${PR_URL////\\/})/ }" "$DOC"
          git config --global user.name oarepo-bot
          git config --global user.email noreply@cesnet.cz
          git add "$DOC"
          git commit -m "PR url - resolves #$ISN2"
          git push --set-upstream origin "$BRANCH"
          echo "Done."
