
name: New RFC

on:
  workflow_dispatch:
    inputs:
      issuenum:
        description: Issue number
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      ISN: ${{ github.event.inputs.issuenum }}
      ISN2: 2
      TEMPLATE: 0000-template.md
      APIURL: https://api.github.com/repos/thlava-cesnet/test1/issues
    steps:
      - name: Checkout oarepo/rfcs
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TH_BOT }}
      - name: with input "#"${{ github.event.inputs.issuenum }}
        run: |
          echo "Test of input, issuenum:${{ github.event.inputs.issuenum }}"
          printf -v ISN_Z "%04d" "$ISN"
          DATE=$(date '+%Y-%m-%d')
          TITLE="$(curl -s "$APIURL/$ISN2" | jq '.title')"
          AUTHOR="$(curl -s "$APIURL/$ISN2" | jq '.user.login')"
          DOC="docs/$ISN_Z-$TITLE.md"
          echo "$DOC - $TITLE ($AUTHOR)"
          echo "----"
          curl -s "$APIURL/$ISN2"
          echo "---- title, login"
          echo "----"
          echo "ISN_Z=$ISN_Z" >> $GITHUB_ENV
          echo "DOC=$DOC" >> $GITHUB_ENV
          cp $TEMPLATE "$DOC"
          sed -i "/^- Start Date:/ s/YYYY-MM-DD/$DATE/" "$DOC"
          sed -i "/^- Authors:/ s/:/: $AUTHOR/" "$DOC"
          sed -i "/^# <RFC title>/ s/<RFC title>/$TITLE/" "$DOC"
      - name: Commit back
        run: |
          echo "Start [$ISN_Z]"
          git config --global user.name oarepo-bot
          git config --global user.email noreply@cesnet.cz
          git checkout -b "rfc-$ISN_Z"
          git add "$DOC"
          git commit -m "commit $ISN_Z"
          git push --set-upstream origin "rfc-$ISN_Z"
          echo "Done."
