name: update index.md

on:
  push:
    paths-ignore: [ 'docs/index.md' ]
  pull_request:
    paths-ignore: [ 'docs/index.md' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      APIURL: https://api.github.com/repos/thlava-cesnet/test1
      RAWURL: https://raw.githubusercontent.com/thlava-cesnet/test1
      INDEX: docs/index.md
    steps:
      - name: Checkout oarepo/rfcs
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TH_BOT }}
      - name: $INDEX regenerate
        run: |
          DATE=$(date '+%Y-%m-%d')
          git branch --format='%(refname:short)'
          BRANCHES="$(curl -s "$APIURL/git/refs/heads" | jq -r '.[]|select(.ref|test("^refs/heads/rfc-")).ref' | sed 's/^refs\/heads\///')"
          # index section from start to regexp:
          sed -n '1,/^<!--ts-->/ p' < $INDEX > $INDEX.tmp
          for BR in $BRANCHES; do echo "BR:>$BR<"
            COMMIT_URL=$(curl -s "$APIURL/git/refs/heads/$BR" | jq -r '.object.url')
            TREE_URL=$(curl -s "$COMMIT_URL" | jq -r '.tree.url')
            DOCS_URL=$(curl -s "$TREE_URL" | jq -r '.tree[]|select(.path=="docs").url')
            RFC_FILE=$(curl -s "$DOCS_URL" | jq -r '.tree[]|select(.path|test("^[0-9]{4}")).path')
            echo "$RFC_FILE"
            TITLE=$(curl -s "$RAWURL/$BR/docs/$RFC_FILE" | sed -n '/^# / { s/^# //; p }')
            echo "TITLE:>$TITLE<"
            # list item:
            echo "* [$BR: $TITLE](../../$BR/docs/$RFC_FILE)" >> $INDEX.tmp
          done
          # index section from regexp to eof:
          sed -n '/^<!--te-->/,$ p' < $INDEX >> $INDEX.tmp
          mv $INDEX.tmp $INDEX
      - name: Commit back
        run: |
          git config --global user.name oarepo-bot
          git config --global user.email noreply@cesnet.cz
          git add $INDEX
          git commit -m "$INDEX regenerate" -m "[skip ci]" && git push
          echo "Done."
