
name: trigerred

on:
  workflow_dispatch:
    inputs:
      profile:
        description: Profile name
        required: false
        default: narodni-repozitar-test

jobs:
  wf-triggered:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: test run ${{ github.event.inputs.profile }}
        run: |
          echo "${{ github.event.inputs.profile }}"
