
name: pull-req

on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
    branches:
      - 'staged-**'
      - 'prod-**'

jobs:
  wf9_1:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: test run ${{ github.event.type }}
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo "$EVENT_CONTEXT"
  if-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: merged ${{ github.event.type }}
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo "The PR was merged: $EVENT_CONTEXT"
