
name: pull-req

on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
    branches: [ staged03 ]
  workflow_dispatch:

jobs:
#  call-workflow:
#    uses: oarepo/oarepo-deployment/.github/workflows/test.yml@main
#    with:
#      profile: "narodni-repozitar-test"
#    secrets:
#      token: ${{ secrets.TH_BOT_230616 }}
  wf9_1:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: test run ${{ github.event.action }}
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo "sender ${{ github.event.sender.login }}"
          echo "$EVENT_CONTEXT"
      - name: Trig workflow on oa/oa-dep
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: oarepo/oarepo-deployment
          workflow: test.yml
          token: ${{ secrets.OAR_BOT4DEP }}
          ref: "main"
          inputs: '{ "profile": "narodni-repozitar-test" }'
  if-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: merged ${{ github.event.action }}
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo "sender ${{ github.event.sender.login }}"
          echo "The PR was merged: $EVENT_CONTEXT"
