# -*- coding: utf-8 -*-
#
# Copyright (C) 2023 CESNET.
#

name: local GHa test 1

on:
  workflow_dispatch:

jobs:
  job1:
    steps:
      - uses: actions/checkout@v3
      - name: Run local GHa
        uses: ./.github/actions/local_1
        with:
          txt1: def
