# -*- coding: utf-8 -*-
#
# Copyright (C) 2023 CESNET.
#

name: local GHa test 1

on:
  workflow_dispatch:
    inputs:
      txt1:
        description: txt1 field
        required: false
        default: abc

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run local GHa
        id: call_local_1
        uses: ./.github/actions/local_1
        with:
          txt1: ${{ inputs.txt1 }}
      - name: Print output
        run: |
          echo "Output: ${{ steps.call_local_1.outputs.out1 }}"
      - name: Done
        run: |
          echo "Done."
