# -*- coding: utf-8 -*-
#
# Copyright (C) 2023 CESNET.
#

name: local GHa test 2
run-name: local GHa test 2 with ${{ inputs.txt1 }} by ${{ github.actor }}

on:
  schedule:
    # min hourGMT dom mon dow
    #- cron: '14 14 * * 5'
    # debug run
    - cron: '50 9 * * *'
  workflow_dispatch:
    inputs:
      txt1:
        description: txt1 field
        required: false
        default: abc

jobs:
  job-local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run local GHa
        id: call_local_1
        uses: ./.github/actions/local_1
        with:
          txt1: ${{ inputs.txt1 }}
      - name: Print output
        run: |
          echo "Output: ${{ steps.call_local_1.outputs.out1 }}"
      - name: mkerr
        run: |
          /bin/false
      - name: Err handler
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mail.cesnet.cz
          subject: ${{ github.job }} (${{ github.repository }}) failed
          to: hlava@cesnet.cz
          from: oarepo@cesnet.cz
          body: ${{ github.job }} in ${{ github.workflow}} of ${{ github.repository }} failed with status ${{ job.status }}
      - name: Done
        run: |
          echo "Done."
  job-remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run remote composite GHa
        id: call_remote_1
        uses: thlava-cesnet/actions-test@v10
        with:
          input1: ${{ inputs.txt1 }}
      - name: Print output
        run: |
          echo "Output: ${{ steps.call_remote_1.outputs.output1 }}"
      - name: Done
        run: |
          echo "Done."
