# -*- coding: utf-8 -*-
#
# Copyright (C) 2023 CESNET.
#

name: services test

on:
  workflow_dispatch:

jobs:
  opensearch:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        opensearch-version: [ 2 ]
    steps:
      - name: opensearch ${{ matrix.opensearch-version }}
        uses: ankane/setup-opensearch@v1
        with:
          opensearch-version: ${{ matrix.opensearch-version }}
      - name: test opensearch on port 9200
        run: |
          netstat -ntlp
          curl http://localhost:9200/
