# -*- coding: utf-8 -*-
#
# Copyright (C) 2023 CESNET.
#

name: services test

on:
  workflow_dispatch:

jobs:
#  opensearch:
#    runs-on: ubuntu-latest
#    strategy:
#      max-parallel: 1
#      matrix:
#        opensearch-version: [ 2 ]
#    env:
#      OPENSEARCH_PORT: 9200
#    steps:
#      - name: opensearch ${{ matrix.opensearch-version }}
#        uses: ankane/setup-opensearch@v1
#        with:
#          opensearch-version: ${{ matrix.opensearch-version }}
#      - name: test opensearch on port ${{ env.OPENSEARCH_PORT }}
#        run: |
#          netstat -ntlp
#          curl http://localhost:${{ env.OPENSEARCH_PORT }}/

  redis:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        redis-version: [ '6', '6.2' ]
    env:
      REDIS_PORT: 6379
    steps:
      - name: redis ${{ matrix.redis-version }}
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: test redis on port ${{ env.REDIS_PORT }}
        run: |
          netstat -ntlp
          redis-cli ping
#          curl http://localhost:${{ env.REDIS_PORT }}/
